---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: _default

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[hollandbackup::default]
      - recipe[hollandbackup::mysqldump]
      - recipe[hollandbackup::main]
      - recipe[hollandbackup::backupsets]
    attributes:

  # Test the installation of holland leveraging the library
  - name: library-install
    run_list:
    - recipe[library-test::install]
    - recipe[library-test::main]

  # Test the installation and then removal of holland leveraging the library
  - name: library-install-uninstall
    run_list:
    - recipe[library-test::install_uninstall]
